### ISSUE TITLE
Feature Request: Only resize resizable windows

### ISSUE THREAD

**Issue by xdaimon** [stefansundin/altdrag#86] opened 2017-11-21 13:54 UTC
I noticed that the installer for a game could be resized with altdrag even though the window could not be resized using just the mouse. The mouse pointer never changes appearance when placed at any edge of the installer's window.

**Comment by mottosso** [comment] 2018-04-11 22:58
I'd counter this request with a request for it to stay. :) It means I do less guesswork about whether a window will or will not resize and feel more in control. Though I can see how it might not be desirable by all for all windows, especially when they cause drawing glitches.

**Comment by Zer0t3ch** [comment] 2018-04-15 15:50
> I'd counter this request with a request for it to stay

I agree. At the very worst, make it configurable. I've used it multiple times to resize windows that scaled just fine but didn't "want" to allow resizing. (Some games are a good example)

**Comment by loligans** [comment] 2019-02-10 04:32
I think blacklisting windows would provide a better solution.

**Comment by dtruebin** [comment] 2020-08-08 08:51
This is a dupe of #31

**Closed** 2020-08-08 18:06 UTC
