### ISSUE TITLE
Snap screen boarders has gaps

### ISSUE THREAD

**Issue by SpikePy** [stefansundin/altdrag#120] opened 2020-06-26 07:26 UTC
When enabling **snap to screen** there is always a gap on the left, right and bottom

![image](https://user-images.githubusercontent.com/16565183/85831844-3a078880-b78f-11ea-90fc-33822049f630.png)

It seems not every application is affected. Steam, MS Teams, Whatsapp are working as expected, maybe because they use Electron for their GUI?
Native windows Applications like File explorer, Firefox, Chrome, Edge (Chromium) and Mail are having the shown gaps.

**Comment by dtruebin** [comment] 2020-08-08 08:59
@SpikePy it's a dupe of #38 
Could you close this one?

**Closed as completed** 2020-08-09 16:14 UTC
