### ISSUE TITLE
Too much magnet.

### ISSUE THREAD

**Issue by mupic** [stefansundin/altdrag#111] opened 2020-02-18 08:43 UTC
Indentation between sticking is too large.
The distance is too far from activating adhesion to the window.
Windows do not magnetize if you do not enable the setting HookWindows = 1

https://yadi.sk/d/n3MXN538EY3deg

**Comment by dtruebin** [comment] 2020-08-08 08:59
@mupic it's a dupe of #38 
Could you close this one?

**Closed** 2020-08-08 09:51 UTC
